name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
          - x64
          - x86
    
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        toolset: 14.35

    - run: |
        cmake --preset=ninja-${{ matrix.arch }}-release
        cmake --build --preset=ninja-${{ matrix.arch }}-release

    - uses: actions/upload-artifact@main
      with:
        name: comon-${{ matrix.arch }}
        path: |
          build/ninja-${{ matrix.arch }}-release/comon/comon.dll
          build/ninja-${{ matrix.arch }}-release/comon/comon.pdb
